import { AIAnalysis } from "@/lib/mockData";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Brain, CheckCircle2, AlertTriangle, TrendingUp, Minus } from "lucide-react";
import { cn } from "@/lib/utils";

export function AIAnalysisCard({ analysis }: { analysis: AIAnalysis }) {
  return (
    <Card className="bg-gradient-to-br from-card to-primary/5 border-primary/20 overflow-hidden relative">
      <div className="absolute top-0 right-0 p-4 opacity-10">
        <Brain className="w-32 h-32" />
      </div>
      
      <CardHeader className="pb-2">
        <div className="flex items-center gap-2">
          <Badge variant="outline" className="bg-primary/10 text-primary border-primary/20 animate-pulse">
            AI INSIGHTS
          </Badge>
          <span className="text-xs text-muted-foreground">Generated by FinSight Engine</span>
        </div>
        <CardTitle className="text-lg pt-2">Analyst Outlook</CardTitle>
      </CardHeader>
      
      <CardContent className="space-y-6 relative z-10">
        <div className="flex items-center gap-4">
          <div className={cn(
            "px-4 py-2 rounded-lg font-bold text-2xl flex items-center gap-2 border",
            analysis.recommendation === "Buy" ? "bg-emerald-500/10 text-emerald-600 border-emerald-500/20" :
            analysis.recommendation === "Sell" ? "bg-rose-500/10 text-rose-600 border-rose-500/20" :
            "bg-amber-500/10 text-amber-600 border-amber-500/20"
          )}>
            {analysis.recommendation === "Buy" && <TrendingUp className="size-6" />}
            {analysis.recommendation === "Sell" && <TrendingUp className="size-6 rotate-180" />}
            {analysis.recommendation === "Hold" && <Minus className="size-6" />}
            {analysis.recommendation.toUpperCase()}
          </div>
          
          <div className="flex flex-col">
            <span className="text-xs text-muted-foreground uppercase font-semibold">Confidence Score</span>
            <div className="flex items-baseline gap-1">
              <span className="text-2xl font-mono font-bold">{analysis.confidence}%</span>
            </div>
          </div>
        </div>

        <div className="space-y-2">
          <p className="text-sm leading-relaxed text-muted-foreground">
            {analysis.summary}
          </p>
        </div>

        <div className="space-y-3 pt-2">
          <h4 className="text-xs font-semibold uppercase text-muted-foreground tracking-wider">Key Factors</h4>
          <div className="flex flex-wrap gap-2">
            {analysis.keyFactors.map((factor, i) => (
              <div key={i} className="flex items-center gap-1.5 text-sm bg-background/50 border rounded-full px-3 py-1">
                <CheckCircle2 className="size-3.5 text-primary" />
                {factor}
              </div>
            ))}
          </div>
        </div>
        
        <div className="pt-4 border-t border-dashed">
          <p className="text-[10px] text-muted-foreground text-center">
            Disclaimer: This is an AI-generated analysis based on historical data patterns. Not financial advice.
          </p>
        </div>
      </CardContent>
    </Card>
  );
}